### ISSUE TITLE
[iOS] Feat - 필터링 결과 없는 경우 화면 변경

### ISSUE THREAD

**Issue by wood0203** [codesquad-members-2023-team2/issue-tracker#127]
사용자 관점에서 필터링 결과가 없는 경우 알 수 있도록 빈 화면을 표시하는 기능을 추가합니다.

**Comment by hyeffie** [comment]
필터 결과가 비어 있는데 이전 결과가 목록에서 사라지지 않음

![empty](https://github.com/codesquad-members-2023-team2/issue-tracker/assets/56967908/709d277e-d336-4dad-a300-9c7a20b50038)
