### ISSUE TITLE
[BE] 1주차 리뷰 (API DOCS, ERD, DDL, Infra)

### ISSUE THREAD

**Issue by acceptor-gyu** [codesquad-members-2023-team2/issue-tracker#26]
- [API DOCS](https://github.com/codesquad-members-2023-team2/issue-tracker/wiki/API-DOCS)
- [ERD](https://github.com/codesquad-members-2023-team2/issue-tracker/wiki/%5BBE%5D-ERD-Diagram)
- [DDL](https://github.com/codesquad-members-2023-team2/issue-tracker/wiki/DDL)
- [Infra](https://github.com/codesquad-members-2023-team2/issue-tracker/wiki/%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%EC%9D%B8%ED%94%84%EB%9D%BC)

**Comment by kses1010** [comment]
프로젝트 개발 환경 및 DB 세팅리뷰입니다!
### API Docs
- 괜찮습니다!
### ERD 및 DDL
- ERD 설계는 지금당장에는 이상없습니다!
- 다만 프로젝트 진행중에 ERD가 계속해서 바뀌더라도 걱정하지마세요 원래 DB 설계는 프로젝트 진행하면서 꾸준히 바뀐답니다!
<img width="431" alt="image" src="https://github.com/codesquad-members-2023-team2/issue-tracker/assets/49144662/16111039-5a0f-45b4-be7a-d14e321eb0af">
- ManyToMany 테이블에서 단독 PK를 지정하지 않은 이유가 무엇인가요? 그렇다면 이렇게 하면 단독 PK와 다중키의 차이점은 무엇인가요?
### 인프라
- 이상없습니다!

**Comment by acceptor-gyu** [comment]
MantToMany 테이블에서 단독 PK를 지정하지 않은 이유는 단순하게 다중키로 PK의 역할을 할 수 있다는 것을 이론적으로 알고 있었고 단독 PK를 지정하게 되면 테이블이 어떻게 만들어지고 쿼리는 어떻게 작성해야하는 것인지 직관적으로 쉽게 이해되지는 않아서 다중키를 사용하게 되었습니다.


- 성능, 인덱스 면을 고려하면 단독 PK를 사용했을 때 컬럼 하나를 사용하기 때문에 인덱스의 크기도 작아지고 컬럼 두 개를 사용하는 것보다 인덱스를 통한 검색 성능이 더 좋을 것이라고 생각합니다.
- 추가적으로 쉽게 와닿지는 않은데 복합키에 비즈니스 종속적인 컬럼이 있으면 변경사항, 향후 확장이 어렵다는 것으로 알고 있습니다.


아직 프로젝트나 데이터베이스까지 다 연결해서 무언가를 만들어 본 경험이 없어서 이론적으로 복합키를 사용하면 된다는 것을 알고 있었는데 단독 PK를 지정하는 것이 더 좋아보입니다.


현업에서는 보통 단독 PK를 지정하기 때문에 저희에게 질문? 또는 생각 해보라고 말씀해주신 것같습니다. 그렇다면 복합키라는 것은 보통 그냥 이론적인 개념인건가요?


> <img alt="image" width="431" src="https://user-images.githubusercontent.com/49144662/238164788-16111039-5a0f-45b4-be7a-d14e321eb0af.png">
> * ManyToMany 테이블에서 단독 PK를 지정하지 않은 이유가 무엇인가요? 그렇다면 이렇게 하면 단독 PK와 다중키의 차이점은 무엇인가요?

**Comment by kses1010** [comment]
단독 PK로 지정할 수도 있고 복합키로 지정할 수 있습니다. 혹시 두개의 차이점에 대해서 학습을 유도하려고 질문드렸습니다!!
사실 두개는 큰 차이가 없습니다. 저도 첫번째회사에선 단독PK를 두번째 회사에선 복합키를 사용했습니다. 
다음 블로그 링크를 참고하시면 좋을듯 합니다.

https://hoonzi-text.tistory.com/104

고생하셨습니다!
